import FooterBarComponent from '@/components/GeralPagesComponents/FooterbarComponent/component';
import NavBarComponent from '@/components/GeralPagesComponents/NavbarComponent/component';
import { ReduxProvider } from '@/store/redux-provider';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '@style/globalStyleCss.css'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <ReduxProvider>
          <NavBarComponent />
          {children}
          <FooterBarComponent />
        </ReduxProvider>
      </body>
    </html>
  );
}