import FooterBarComponent from '@/components/GeralPagesComponents/FooterbarComponent/component';
import NavBarComponent from '@/components/GeralPagesComponents/NavbarComponent/component';
import '@style/globalStyleCss.css'
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  weight: ['400', '500', '600', '700'], // adicione os pesos usados
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <NavBarComponent />
        {children}
        <FooterBarComponent />
      </body>
    </html>
  );
}
