import FooterBarComponent from '@/components/GeralPagesComponents/FooterbarComponent/component';
import NavBarComponent from '@/components/GeralPagesComponents/NavbarComponent/component';
import { persistor, store } from '@/store';
import '@style/globalStyleCss.css'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Provider } from 'react-redux';
import { PersistGate } from 'redux-persist/integration/react';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  weight: ['400', '500', '600', '700'], // adicione os pesos usados
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <Provider store={store}>
          <PersistGate loading={null} persistor={persistor}>
            <NavBarComponent />
            {children}
            <FooterBarComponent />
          </PersistGate>
        </Provider>
      </body>
    </html>
  );
}
